// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXW4zg1o_cMgDREwviQgbvImRtsBWv8A0',
    appId: '1:394795281480:web:e3f937b8584649103a3c7d',
    messagingSenderId: '394795281480',
    projectId: 'devcodex-e78be',
    authDomain: 'devcodex-e78be.firebaseapp.com',
    storageBucket: 'devcodex-e78be.appspot.com',
    measurementId: 'G-2BV40ZG7MR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFDLbvm5bZWfPDqq1sSOWW9-0U5At-vbU',
    appId: '1:394795281480:android:cdd303c53d64ddc93a3c7d',
    messagingSenderId: '394795281480',
    projectId: 'devcodex-e78be',
    storageBucket: 'devcodex-e78be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXXYCE4H7JhYe-d8s9GNaVBqSou3lkPtM',
    appId: '1:394795281480:ios:712a2e234aad2e683a3c7d',
    messagingSenderId: '394795281480',
    projectId: 'devcodex-e78be',
    storageBucket: 'devcodex-e78be.appspot.com',
    iosClientId: '394795281480-1rudls6f9ino4cduurden2cvvr1p02a8.apps.googleusercontent.com',
    iosBundleId: 'com.example.DevCodeX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXXYCE4H7JhYe-d8s9GNaVBqSou3lkPtM',
    appId: '1:394795281480:ios:712a2e234aad2e683a3c7d',
    messagingSenderId: '394795281480',
    projectId: 'devcodex-e78be',
    storageBucket: 'devcodex-e78be.appspot.com',
    iosClientId: '394795281480-1rudls6f9ino4cduurden2cvvr1p02a8.apps.googleusercontent.com',
    iosBundleId: 'com.example.DevCodeX',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXW4zg1o_cMgDREwviQgbvImRtsBWv8A0',
    appId: '1:394795281480:web:e1347698c30d78073a3c7d',
    messagingSenderId: '394795281480',
    projectId: 'devcodex-e78be',
    authDomain: 'devcodex-e78be.firebaseapp.com',
    storageBucket: 'devcodex-e78be.appspot.com',
    measurementId: 'G-GF1PX6PFKX',
  );

}